FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    git \
    # build-essential \
    # pkg-config \
    # python3-dev \
    # libcairo2-dev \
    # libpango1.0-dev \
    # ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir uv mcpo

CMD ["python", "run_server.py"]