FROM jupyter/minimal-notebook:latest

# Install system build dependencies for pycairo, manimpango, manim
USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    python3-dev \
    libcairo2-dev \
    libpango1.0-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Back to notebook user
USER $NB_UID

# Install Python dependencies
RUN pip install --no-cache-dir pandas==2.3.2 manim==0.19.0 manimlib==0.2.0 manimgl==1.7.2 \
typing-extensions==4.15.0